// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBorxEOPGJpTH6_ekDDsGm29wCsMFBgtME',
    appId: '1:860449703802:web:778f683a5c9d8dbfee38c3',
    messagingSenderId: '860449703802',
    projectId: 'ecommerce-project-b0b64',
    authDomain: 'ecommerce-project-b0b64.firebaseapp.com',
    storageBucket: 'ecommerce-project-b0b64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYJKzMDoK1q4WotpiB3WSiOBQWIyXq64Q',
    appId: '1:860449703802:android:90b892c89bb8db6dee38c3',
    messagingSenderId: '860449703802',
    projectId: 'ecommerce-project-b0b64',
    storageBucket: 'ecommerce-project-b0b64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4pCOIi6CifpqMoJKllTaBho3mxUoXRC0',
    appId: '1:860449703802:ios:5cf986c4ea1a9233ee38c3',
    messagingSenderId: '860449703802',
    projectId: 'ecommerce-project-b0b64',
    storageBucket: 'ecommerce-project-b0b64.firebasestorage.app',
    androidClientId: '860449703802-83hp1fo705qoh55g45l3af665v03vdib.apps.googleusercontent.com',
    iosClientId: '860449703802-liqjq7ude7jn272ghlirsm4je7op4beu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceProject',
  );

}